Android.bp: Fix v4l2_params build errors
Add the newly introduced v4l2_params.cpp source to the
neo_ipa_uguzzi package source list.

Also add 'utils' folder to include dir list to prevent below error:

vendor/nxp/neo-ipa-uguzzi/utils/params.h:19:10: error: 'libipa/v4l2_params.h' file not found with <angled> include; use "quotes" instead
   19 | #include <libipa/v4l2_params.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
      |          "libipa/v4l2_params.h

Signed-off-by: Antoine Bouyer <antoine.bouyer@nxp.com>